title: Hermes Application
lsi: false
safe: true
remote_theme: pmarsceill/just-the-docs
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

callouts:
  highrisk:
    title:
    color: red
  mediumhighrisk:
    title:
    color: orange
  mediumrisk:
    title:
    color: yellow
  lowrisk:
    title:
    color: green